### PR TITLE
Initial work getting binder going

### PR DESCRIPTION
**Pull request by jni**
@sofroniewn I still can't get this to work for some reason. Going commit by commit should show you what I tried, but it amounts to:

- copying the binder folder wholesale from https://github.com/manics/jupyter-omeroanalysis-desktop/tree/napari-binder
- copying the jupyter_desktop folder wholesale from the same repo
- removing OMERO.insight stuff
- changing the requirements to use pip instead of conda

When I try to launch the desktop, I get a "500 internal server error" "could not start desktop in time" page.

@manics if you have a few minutes, do you have any idea what I might be doing wrong here? I did move the Python env to pip from conda, but that shouldn't make a difference? Or is your version of websockify patched?

You can find this branch here:

https://github.com/jni/napari-training-course/tree/binder

and try binder here:

https://mybinder.org/v2/gh/jni/napari-training-course/binder

### CODE REVIEW

**Comment by manics** [comment]
@jni websockify isn't patched, but the conda package compiles a library that's not included in the pypi package:
https://github.com/manics/conda-websockify/blob/4fc7e06bbb14371b3d6a8c9f06f8c53b592419fa/build.sh#L8-L9

This is to enable the [Wrap a Program function](https://github.com/novnc/websockify#wrap-a-program) that lets websockify take care of running VNC. The alternative is to run websockify and VNC separately, but then you need a process manager or some other way to manage two processes.

**Comment by jni** [comment]
@manics Thank you so much for chiming in! Building now... :crossed_fingers: I just noticed that there's no Python 3.8 package! Nothing urgent (just downgraded to 3.7), but maybe you'd like to create one for future users? =)

Thanks again!

**Comment by jni** [comment]
@manics Ok, so now I can launch the desktop (:tada:), but napari fails without being able to detect the Qt loop. I think that's because launching the Qt loop failed. When I try it manually with a `napari.gui_qt()` context, I get the following error:

```
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

Do you think that's another difference between conda-forge qt and pip's?

@sofroniewn I need to get to bed, I think the next thing I would try here is installing as many dependencies as possible from conda-forge, *using PyQt5*, and then installing napari without dependencies as done by @manics originally. I thought I could get away from that but maybe not. :grimacing: 

Note also that the notebooks will need these lines at the top of the notebooks when running in binder:

```python
# Use the novnc Desktop in the other window
import os
os.environ['DISPLAY'] = ':1.0'
```

I'd suggest putting them in all the notebooks and commenting them out, with a note that they should be uncommented when running on binder.

**Comment by manics** [comment]
I've just pushed a Linux Python 3.8 update 😀

I remember having problems when mixing pyqt from conda and napari from pip, caused by the pyqt conda package not appearing in `pip list`, which is why I had to disable dependencies when installing with pip.

For the binder/non-binder setup you could check for the presence of the `BINDER_SERVICE_HOST` environment variable:
https://discourse.jupyter.org/t/check-if-running-on-binder/635/7

**Comment by jni** [comment]
Ok @sofroniewn this should be ready to merge! :tada: Thank you so much @manics for all the help and for creating the source napari-binder repo in the first place! :pray: :pray: :pray: 

@sofroniewn Once merged, you should run through the binder links at least once so that binder has a cached image for this repo. That'll make boot much faster for participants.

Also I recommend clearing the notebooks and running through them one more time so that cells are numbered 1-n rather than starting at random numbers. :grimacing: I can also do this for you once the repo stabilises.

**Comment by sofroniewn** [comment]
Ok, thanks so much @jni and @manics - will look over now and then merge and test as you mentioned!

**Pull request merged**
